### ISSUE TITLE
Unable to get the bot running

### ISSUE THREAD

**Issue by Arkmull** [TimothyCole/Twitch-to-Discord-Relay-NodeJs#1]
I have zero knowledge on running the javascript in Windows OS.
I have read up a bit and tried running the run.js on command prompt after entering npm install discord.js before entering node {directory}run.js

this is the return error

    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\Desktop\bot\run.js:3:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

C:\WINDOWS\system32>

**Comment by TimothyCole** [comment]
This no longer works do to discord API changes and no I don't plan on updating it, it's useless to me sorry.
